name: saxovat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  mask_text_input_formatter: ^2.5.0
  swipe_cards: ^2.0.0+1
  intro_screen_onboarding_flutter: ^1.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  firebase_auth: ^4.11.1
  firebase_auth_platform_interface: ^7.0.1
  swipe_image_gallery: ^0.8.3
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.12.1
  uuid: ^4.1.0
  easy_image_viewer: ^1.2.1
  cached_network_image: ^3.3.0
  firebase_crashlytics: ^3.4.3
  firebase_performance: ^0.9.3+3

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_photo/main.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/masjid/
     - assets/images/main_photo/main.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
