name: saxovat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  mask_text_input_formatter: ^2.5.0
  swipe_cards: ^2.0.0+1
  intro_screen_onboarding_flutter: ^1.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  firebase_auth: ^4.11.1
  firebase_auth_platform_interface: ^7.0.1
  swipe_image_gallery: ^0.8.3
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.7



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/masjid/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
