// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsps2zNt2B0fXNhmzXYvDynmMvbIpdUlE',
    appId: '1:678158787297:web:ec1de4aaf6cedb32ab0da0',
    messagingSenderId: '678158787297',
    projectId: 'saxovat-26672',
    authDomain: 'saxovat-26672.firebaseapp.com',
    storageBucket: 'saxovat-26672.appspot.com',
    measurementId: 'G-VJ3JQGFTS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHf4Z731u_botSLvjN4LrZ8XyTitkCuA0',
    appId: '1:678158787297:android:a11b1a2f66615ba3ab0da0',
    messagingSenderId: '678158787297',
    projectId: 'saxovat-26672',
    storageBucket: 'saxovat-26672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoaA0_zmJs2Y_1VekhTR2PXnSOqKSTw7I',
    appId: '1:678158787297:ios:e3870f6a10a64dddab0da0',
    messagingSenderId: '678158787297',
    projectId: 'saxovat-26672',
    storageBucket: 'saxovat-26672.appspot.com',
    iosBundleId: 'com.example.saxovat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoaA0_zmJs2Y_1VekhTR2PXnSOqKSTw7I',
    appId: '1:678158787297:ios:2536853125b6974bab0da0',
    messagingSenderId: '678158787297',
    projectId: 'saxovat-26672',
    storageBucket: 'saxovat-26672.appspot.com',
    iosBundleId: 'com.example.saxovat.RunnerTests',
  );
}
